var res = Response {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  res: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: false,
     domain: null,
     _events: { end: [Object], error: [Object], close: [Function: bound emit] },
     _eventsCount: 3,
     _maxListeners: undefined,
     socket: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'bbs.byr.cn',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 386,
        _bytesDispatched: 890,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'bbs.byr.cn',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 386,
        _bytesDispatched: 890,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { date: 'Tue, 22 Dec 2015 05:13:41 GMT',
        server: 'Apache/2.2.21 (Unix) PHP/5.3.10',
        'x-powered-by': 'PHP/5.3.10',
        'set-cookie': [Object],
        vary: 'Accept-Encoding',
        'content-encoding': 'gzip',
        'content-length': '73',
        connection: 'close',
        'content-type': 'application/json;charset=GBK' },
     rawHeaders: 
      [ 'Date',
        'Tue, 22 Dec 2015 05:13:41 GMT',
        'Server',
        'Apache/2.2.21 (Unix) PHP/5.3.10',
        'X-Powered-By',
        'PHP/5.3.10',
        'Set-Cookie',
        'nforum[XWJOKE]=hoho; path=/; domain=bbs.byr.cn',
        'Vary',
        'Accept-Encoding',
        'Content-Encoding',
        'gzip',
        'Content-Length',
        '73',
        'Connection',
        'close',
        'Content-Type',
        'application/json;charset=GBK' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 200,
     statusMessage: 'OK',
     client: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'bbs.byr.cn',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 386,
        _bytesDispatched: 890,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: 229,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /article/Talking/ajax_post.json HTTP/1.1\r\nHost: bbs.byr.cn\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.6.1\r\nContent-Type: application/json\r\nX-Requested-With: XMLHttpRequest\r\nX-API-Key: foobar\r\nAccept: application/json\r\nCookie: nforum-left=100; left-index=0000000000; login-user=anthozoan77; nforum[UTMPUSERID]=anthozoan77; nforum[PASSWORD]=Ole%2B7KFEZbqJ39sFUTe02w%3D%3D; nforum[BMODE]=2; nforum[UTMPKEY]=8108361; nforum[UTMPNUM]=2458; Hm_lvt_38b0e830a659ea9a05888b924f641842=1450612821,1450695262,1450699970,1450751923; Hm_lpvt_38b0e830a659ea9a05888b924f641842=1450758822; nforum[XWJOKE]=hoho\r\nContent-Length: 229\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/article/Talking/ajax_post.json',
        parser: null,
        res: [Circular] },
     setEncoding: [Function],
     on: [Function],
     text: '{"ajax_st":0,"ajax_code":"0400","ajax_msg":"没有指定文章标题"}',
     read: [Function],
     body: undefined },
  request: 
   Request {
     domain: null,
     _events: { end: [Function: bound ] },
     _eventsCount: 1,
     _maxListeners: undefined,
     _agent: false,
     _formData: null,
     method: 'POST',
     url: 'http://bbs.byr.cn/article/Talking/ajax_post.json',
     header: {},
     writable: true,
     _redirects: 0,
     _maxRedirects: 5,
     cookies: '',
     qs: {},
     qsRaw: [],
     _redirectList: [],
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: 229,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /article/Talking/ajax_post.json HTTP/1.1\r\nHost: bbs.byr.cn\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.6.1\r\nContent-Type: application/json\r\nX-Requested-With: XMLHttpRequest\r\nX-API-Key: foobar\r\nAccept: application/json\r\nCookie: nforum-left=100; left-index=0000000000; login-user=anthozoan77; nforum[UTMPUSERID]=anthozoan77; nforum[PASSWORD]=Ole%2B7KFEZbqJ39sFUTe02w%3D%3D; nforum[BMODE]=2; nforum[UTMPKEY]=8108361; nforum[UTMPNUM]=2458; Hm_lvt_38b0e830a659ea9a05888b924f641842=1450612821,1450695262,1450699970,1450751923; Hm_lpvt_38b0e830a659ea9a05888b924f641842=1450758822; nforum[XWJOKE]=hoho\r\nContent-Length: 229\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/article/Talking/ajax_post.json',
        parser: null,
        res: [Object] },
     protocol: 'http:',
     host: 'bbs.byr.cn',
     _data: 
      { content: 'study',
        id: '5767389',
        subject: 'Re%3A%20%E5%8D%81%E5%A4%A7%E7%83%AD%E9%97%A8%E8%AF%9D%E9%A2%98%20%E6%AF%8F%E6%AC%A1%E5%90%8E%E9%9D%A2%E9%83%BD%E6%9C%89%E4%B8%80%E4%B8%AA%E7%BA%A2%E8%89%B2%E7%9A%84%E6%95%B0%E5%AD%97' },
     _parser: [Function],
     _callback: [Function],
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 200,
        statusMessage: 'OK',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        setEncoding: [Function],
        on: [Function],
        text: '{"ajax_st":0,"ajax_code":"0400","ajax_msg":"没有指定文章标题"}',
        read: [Function],
        body: undefined },
     response: [Circular],
     _timeout: 0,
     called: true },
  req: 
   ClientRequest {
     domain: null,
     _events: { drain: [Function], error: [Function], response: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedHeader: { 'content-length': false },
     _contentLength: 229,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'bbs.byr.cn',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 386,
        _bytesDispatched: 890,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'bbs.byr.cn',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 386,
        _bytesDispatched: 890,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _header: 'POST /article/Talking/ajax_post.json HTTP/1.1\r\nHost: bbs.byr.cn\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/1.6.1\r\nContent-Type: application/json\r\nX-Requested-With: XMLHttpRequest\r\nX-API-Key: foobar\r\nAccept: application/json\r\nCookie: nforum-left=100; left-index=0000000000; login-user=anthozoan77; nforum[UTMPUSERID]=anthozoan77; nforum[PASSWORD]=Ole%2B7KFEZbqJ39sFUTe02w%3D%3D; nforum[BMODE]=2; nforum[UTMPKEY]=8108361; nforum[UTMPNUM]=2458; Hm_lvt_38b0e830a659ea9a05888b924f641842=1450612821,1450695262,1450699970,1450751923; Hm_lpvt_38b0e830a659ea9a05888b924f641842=1450758822; nforum[XWJOKE]=hoho\r\nContent-Length: 229\r\nConnection: close\r\n\r\n',
     _headers: 
      { host: 'bbs.byr.cn',
        'accept-encoding': 'gzip, deflate',
        'user-agent': 'node-superagent/1.6.1',
        'content-type': 'application/json',
        'x-requested-with': 'XMLHttpRequest',
        'x-api-key': 'foobar',
        accept: 'application/json',
        cookie: 'nforum-left=100; left-index=0000000000; login-user=anthozoan77; nforum[UTMPUSERID]=anthozoan77; nforum[PASSWORD]=Ole%2B7KFEZbqJ39sFUTe02w%3D%3D; nforum[BMODE]=2; nforum[UTMPKEY]=8108361; nforum[UTMPNUM]=2458; Hm_lvt_38b0e830a659ea9a05888b924f641842=1450612821,1450695262,1450699970,1450751923; Hm_lpvt_38b0e830a659ea9a05888b924f641842=1450758822; nforum[XWJOKE]=hoho',
        'content-length': 229 },
     _headerNames: 
      { host: 'Host',
        'accept-encoding': 'Accept-Encoding',
        'user-agent': 'User-Agent',
        'content-type': 'Content-Type',
        'x-requested-with': 'X-Requested-With',
        'x-api-key': 'X-API-Key',
        accept: 'Accept',
        cookie: 'Cookie',
        'content-length': 'Content-Length' },
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     method: 'POST',
     path: '/article/Talking/ajax_post.json',
     parser: null,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 200,
        statusMessage: 'OK',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        setEncoding: [Function],
        on: [Function],
        text: '{"ajax_st":0,"ajax_code":"0400","ajax_msg":"没有指定文章标题"}',
        read: [Function],
        body: undefined } },
  links: {},
  text: '{"ajax_st":0,"ajax_code":"0400","ajax_msg":"没有指定文章标题"}',
  body: {},
  files: {},
  buffered: true,
  headers: 
   { date: 'Tue, 22 Dec 2015 05:13:41 GMT',
     server: 'Apache/2.2.21 (Unix) PHP/5.3.10',
     'x-powered-by': 'PHP/5.3.10',
     'set-cookie': [ 'nforum[XWJOKE]=hoho; path=/; domain=bbs.byr.cn' ],
     vary: 'Accept-Encoding',
     'content-encoding': 'gzip',
     'content-length': '73',
     connection: 'close',
     'content-type': 'application/json;charset=GBK' },
  header: 
   { date: 'Tue, 22 Dec 2015 05:13:41 GMT',
     server: 'Apache/2.2.21 (Unix) PHP/5.3.10',
     'x-powered-by': 'PHP/5.3.10',
     'set-cookie': [ 'nforum[XWJOKE]=hoho; path=/; domain=bbs.byr.cn' ],
     vary: 'Accept-Encoding',
     'content-encoding': 'gzip',
     'content-length': '73',
     connection: 'close',
     'content-type': 'application/json;charset=GBK' },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
  charset: 'GBK',
  type: 'application/json',
  setEncoding: [Function: bound ],
  redirects: [] 
};
