{ date: 'Tue, 22 Dec 2015 08:57:46 GMT',
  server: 'Apache/2.2.21 (Unix) PHP/5.3.10',
  'x-powered-by': 'PHP/5.3.10',
  'set-cookie': 
   [ 'nforum[UTMPUSERID]=guest; path=/; domain=bbs.byr.cn',
     'nforum[UTMPKEY]=4289383; path=/; domain=bbs.byr.cn',
     'nforum[UTMPNUM]=26664; path=/; domain=bbs.byr.cn',
     'nforum[UTMPUSERID]=anthozoan77; path=/; domain=bbs.byr.cn',
     'nforum[UTMPKEY]=32366852; path=/; domain=bbs.byr.cn',
     'nforum[UTMPNUM]=346; path=/; domain=bbs.byr.cn',
     'nforum[PASSWORD]=I87%2FvLcEzHdtT6PS2WZiOQ%3D%3D; path=/; domain=bbs.byr.cn' ],
  expires: 'Thu, 18 Feb 1988 01:00:00 GMT',
  'cache-control': 'no-store, no-cache, must-revalidate',
  pragma: 'no-cache',
  vary: 'Accept-Encoding',
  'content-encoding': 'gzip',
  'content-length': '445',
  connection: 'close',
  'content-type': 'application/json;charset=GBK' }
